/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.videojuegolaberinto_c4h043.vista;

import com.mycompany.videojuegolaberinto_c4h043.controlador.ControladorPrincipal;

/**
 *
 * @author mcalf
 */
public class GUIPrincipal extends javax.swing.JFrame {
    // Clase que representa la ventana principal del juego.
    // Extiende JFrame para proporcionar la interfaz gráfica inicial del juego.

//Constructor que crea una nueva instancia de GUIPrincipal.
 
    public GUIPrincipal(ControladorPrincipal controlador) {
        initComponents(); // Inicializa los componentes generados automáticamente por NetBeans.
        escuchar(controlador); // Configura el controlador para manejar los eventos de esta ventana.
    }

//Método que asocia los botones de la ventana con el controlador.

    public void escuchar(ControladorPrincipal controlador) {
        btnInstrucciones.addActionListener(controlador); // Asocia el botón "Instrucciones" con el controlador.
        btnHistoria.addActionListener(controlador); // Asocia el botón "Historia" con el controlador.
        btnJugar.addActionListener(controlador); // Asocia el botón "Jugar" con el controlador.
        btnSalir.addActionListener(controlador); // Asocia el botón "Salir" con el controlador.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnJugar = new javax.swing.JButton();
        btnInstrucciones = new javax.swing.JButton();
        btnHistoria = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnJugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnPlay.png"))); // NOI18N
        btnJugar.setActionCommand("jugar");
        btnJugar.setBorderPainted(false);
        btnJugar.setContentAreaFilled(false);
        btnJugar.setDefaultCapable(false);
        getContentPane().add(btnJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, -1, -1));

        btnInstrucciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnInstrucciones.png"))); // NOI18N
        btnInstrucciones.setActionCommand("instrucciones");
        btnInstrucciones.setBorderPainted(false);
        btnInstrucciones.setContentAreaFilled(false);
        btnInstrucciones.setDefaultCapable(false);
        getContentPane().add(btnInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 510, -1, -1));

        btnHistoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnHistoria.png"))); // NOI18N
        btnHistoria.setActionCommand("historia");
        btnHistoria.setBorderPainted(false);
        btnHistoria.setContentAreaFilled(false);
        btnHistoria.setDefaultCapable(false);
        btnHistoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoriaActionPerformed(evt);
            }
        });
        getContentPane().add(btnHistoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 510, -1, -1));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnSalir.png"))); // NOI18N
        btnSalir.setActionCommand("salir");
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setDefaultCapable(false);
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 510, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PortadaExp.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHistoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHistoriaActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHistoria;
    private javax.swing.JButton btnInstrucciones;
    private javax.swing.JButton btnJugar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
